version: '3.8'

services:
  collecting_data_site:
    build:
      context: ./collecting_data_site
    command: python main.py
    restart: always
    container_name: docker_collecting_data_site
    environment:
      - DATABASE_URL=postgres://postgres:qwer1234@db:5432/clients_test_db
    volumes:
      - ./collecting_data_site:/collecting_data_site
    ports:
      - "80:5000"
    depends_on:
      - db
  statistic_site:
    build:
      context: ./statistic_site
    command: python main.py
    restart: always
    container_name: docker_statistic_site
    environment:
      - DATABASE_URL=postgres://postgres:qwer1234@db:5432/clients_test_db
    volumes:
      - ./statistic_site:/statistic_site
    ports:
      - "8888:5001"
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    container_name: docker-db
    hostname: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DATABSE: clients_test_db
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: docker-pgadmin
    hostname: pgadmin
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@ksiloq.ru
      - PGADMIN_DEFAULT_PASSWORD=qwer1234
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5555:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  pg_db:
  pgadmin-data: